name: build

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: [1.15.x, 1.16.x]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install pkg-config libwayland-dev libx11-dev libx11-xcb-dev libxkbcommon-x11-dev libgles2-mesa-dev libegl1-mesa-dev libffi-dev libxcursor-dev

    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ matrix.os }}-go-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}
        restore-keys: ${{ runner.os }}-go-${{ matrix.go }}-

    - name: Build Gio
      run: |
        go run tools/mage.go build:gio

    - name: Build Fyne
      if: matrix.os != 'ubuntu-latest'
      run: |
        go run tools/mage.go build:fyne
