name: build

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [macos-latest, windows-latest]
        go: [1.14.x, 1.15.x]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install Native Dependencies
      run: sudo apt-get install libwayland-dev libx11-dev libxkbcommon-x11-dev libgles2-mesa-dev libegl1-mesa-dev libffi-dev
      if: matrix.os == 'ubuntu-latest'

    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - uses: actions/checkout@v1

    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: build
      run: |
        go run mage.go buildGio
