name: build

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: [1.14.x, 1.15.x]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install libwayland-dev libxkbcommon-x11-dev libgles2-mesa-dev libegl1-mesa-dev libffi-dev

    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - uses: actions/checkout@v1

    - uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ matrix.os }}-go-${{ matrix.go }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ matrix.go }}-

    - name: Build Gio
      run: |
        go run mage.go buildGio

    - name: Build Fyne
      if: matrix.os != 'ubuntu-latest'
      run: |
        go run mage.go buildFyne

    - name: Build Lorca
      run: |
        go run mage.go buildLorca
